site_name: JASMINE Developer's Guide
site_url:
site_author: JASMINE E2E Simulation
site_description:
  JASMINE E2E Simulation Developer's Guide

repo_name:
repo_url: https://github.com/JASMINE-Mission/devguide
edit_uri: ""

copyright: JASMINE E2E 2022

theme:
  name: "material"
  icon:
    logo: material/star-shooting-outline
  favicon: assets/images/jasmine_outline.png
  languatge: "en"
  palette:
    scheme: default
    primary: grey
    accent: deep orange
  features:
    - navigation.sections
    - header.autohide

extra_css:
  - css/config_local.css
extra_javascript:
  - js/config_mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search:
      lang: 'ja'
  - img2fig

markdown_extensions:
  - toc:
      toc_depth: 3
  - extra
  - admonition
  - smarty
  - sane_lists
  - meta
  - attr_list
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.snippets:
      base_path: 'docs'
      check_paths: True
  - pymdownx.arithmatex:
      generic: true

nav:
  - トップページ: index.md
  - はじめに:
    - startup/setup.md
    - startup/guideline.md
    - startup/clearcode.md
    - startup/review.md
    - startup/test.md
  - チュートリアル:
    - dummy: dummy
  - reference.md
  - Links:
    - JASMINE Project: http://jasmine.nao.ac.jp/
    - GitHub Group: https://github.com/JASMINE-Mission/
